import React from 'react';
import { Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  summaryBox: {
    backgroundColor: '#FF4542',
    borderRadius: 8,
    padding: 15,
    marginBottom: 20,
  },
  summaryTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
  },
  summaryText: {
    fontSize: 10,
    color: 'white',
    lineHeight: 1.4,
  },
  boldText: {
    fontWeight: 'bold',
  },
  footer: {
    marginTop: 30,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: '#ddd',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 8,
    color: '#666',
    textAlign: 'center',
    marginBottom: 2,
  },
});

interface AnalysisSummaryProps {
  totalCount: number;
  successfulTriangles: number;
  dominantType: string;
  dominantCount: number;
  dominantPercentage: number;
  avgConfidence: number;
  confidenceQuality: string;
}

export const AnalysisSummary: React.FC<AnalysisSummaryProps> = ({
  totalCount,
  successfulTriangles,
  dominantType,
  dominantCount,
  dominantPercentage,
  avgConfidence,
  confidenceQuality,
}) => {
  return (
    <>
      <View style={styles.summaryBox}>
        <Text style={styles.summaryTitle}>Analysis Summary:</Text>
        <Text style={styles.summaryText}>
          Detected {totalCount} hair follicles with {successfulTriangles} successful directional analyses. 
          The dominant hair type is <Text style={styles.boldText}>{dominantType}</Text> with {dominantCount} follicles ({dominantPercentage.toFixed(1)}% of total).
          Average detection confidence across all follicles is {avgConfidence.toFixed(1)}%, indicating <Text style={styles.boldText}>{confidenceQuality}</Text> detection quality.
        </Text>
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          Generated by Hair Follicle Analysis System | {new Date().toLocaleDateString()}
        </Text>
        <Text style={styles.footerText}>
          This report is for research and analysis purposes. Consult a medical professional for clinical interpretation.
        </Text>
      </View>
    </>
  );
};
